# Re-export all defaults for convenient access: `from config import INITIAL_CAPITAL`
from config.defaults import (  # noqa: F401
    # Capital & Financial
    INITIAL_CAPITAL,
    RISK_FREE_RATE,
    # Time
    TRADING_DAYS_PER_YEAR,
    DAYS_PER_YEAR,
    # Selection
    DEFAULT_SELECTION_TYPE,
    DEFAULT_CATEGORY_SCHEME,
    DEFAULT_CATEGORY_COUNTS,
    DEFAULT_CATEGORY_WEIGHTS,
    DEFAULT_SELECTION_METHOD,
    DEFAULT_MIN_PROB_THRESHOLD,
    DEFAULT_WEIGHTING_SCHEME,
    DEFAULT_TPSL_CATEGORY_DIMENSION,
    DEFAULT_TOP_K,
    DEFAULT_TOP_K_WEIGHTING,
    RISK_ADJUSTED_EPSILON,
    # Entry
    DEFAULT_ENTRY_PRICE_WINDOW,
    # TP / SL
    DEFAULT_TP_MODE,
    DEFAULT_SL_MODE,
    DEFAULT_TP_ENABLED,
    DEFAULT_SL_ENABLED,
    DEFAULT_TPSL_FALLBACK_PCT,
    # ATR
    DEFAULT_ATR_PERIOD,
    DEFAULT_ATR_TP_MULTIPLIER,
    DEFAULT_ATR_SL_MULTIPLIER,
    ATR_SL_FLOOR_FACTOR,
    # Pivot
    DEFAULT_PIVOT_LOOKBACK_DAYS,
    DEFAULT_PIVOT_TP_LEVEL,
    DEFAULT_PIVOT_SL_LEVEL,
    PIVOT_TP_FALLBACK_FACTOR,
    PIVOT_SL_FALLBACK_FACTOR,
    # Flat
    DEFAULT_FLAT_TP_PCT,
    DEFAULT_FLAT_SL_PCT,
    # Index exit / Regime
    DEFAULT_REGIME_FILTER_ENABLED,
    DEFAULT_REGIME_MA_PERIOD,
    DEFAULT_REGIME_EXIT_THRESHOLD,
    DEFAULT_VOL_ADJUSTMENT_ENABLED,
    DEFAULT_VOL_LOOKBACK,
    DEFAULT_HIGH_VOL_THRESHOLD,
    DEFAULT_LOW_VOL_THRESHOLD,
    DEFAULT_HIGH_VOL_MULTIPLIER,
    DEFAULT_LOW_VOL_MULTIPLIER,
    # Reporting
    VAR_CONFIDENCE_LEVEL,
    DEFAULT_ROLLING_WINDOWS,
    DEFAULT_CALENDAR_PERIODS,
    DEFAULT_ROLLING_ALPHA_WINDOW,
    DEFAULT_ROLLING_VOL_WINDOW,
    DEFAULT_ROLLING_SHARPE_WINDOW,
    ANNUALIZATION_FACTORS,
    SCALE_FACTORS,
    # Data validation
    DEFAULT_MIN_PRICES_REQUIRED,
    DEFAULT_ENTRY_WINDOW_LENGTH,
    # Tuning
    DEFAULT_OBJECTIVE,
    DEFAULT_DIRECTION,
    DEFAULT_FAILURE_PENALTY,
    DEFAULT_FAILURE_PENALTY_MINIMIZE,
    DEFAULT_CALMAR_CAP,
    DEFAULT_SAMPLER,
    DEFAULT_MULTI_OBJ_SAMPLER,
    SAMPLER_SEED,
    DEFAULT_TIERED_TP_THRESHOLDS,
    DEFAULT_TIERED_SL_THRESHOLDS,
    DEFAULT_INDEPENDENT_TPSL_MODES,
    # Paths
    DEFAULT_CONFIG_PATH,
    DEFAULT_TUNING_CONFIG_PATH,
    DEFAULT_OUTPUT_BASE_DIR,
    # Misc
    DEFAULT_RUN_STOCK_SELECTION,
    DEFAULT_GENERATE_REPORT,
)

# Schema models
from config.schema import (  # noqa: F401
    BacktestConfig,
    TopKConfig,
    TieredConfig,
    AtrConfig,
    PivotConfig,
    FlatConfig,
    RegimeFilterConfig,
    VolAdjustmentConfig,
    IndexExitConfig,
)
