from typing import Optional

import numpy as np
import pandas as pd
import warnings
from config.defaults import INITIAL_CAPITAL, DEFAULT_ENTRY_PRICE_WINDOW, TRADING_DAYS_PER_YEAR
from utils.quarter import get_quarter_dates
from utils.logging_config import get_logger

logger = get_logger(__name__)

# --------------------------------------------------------------------------------
# 1. POSITION SIZING LOGIC
# --------------------------------------------------------------------------------

def calculate_position_sizes(quarterly_pf_stocks: pd.DataFrame, total_capital: float) -> pd.DataFrame:
    """
    Allocates capital to each stock using stock_weight.
    
    Uses the 'stock_weight' column to directly allocate capital to each stock.
    The stock_weight column should sum to approximately 1.0 per quarter.

    Returns:
        the passed dataframe with additional cols: [allocated_capital, shares]
    """
    # Create a copy to avoid SettingWithCopy warnings
    quarterly_pf_stocks = quarterly_pf_stocks.copy()
    
    if 'stock_weight' not in quarterly_pf_stocks.columns:
        raise ValueError("Missing required column 'stock_weight' in quarterly_pf_stocks")
    
    # Direct allocation using stock_weight
    quarterly_pf_stocks['allocated_capital'] = total_capital * quarterly_pf_stocks['stock_weight']
    
    # Calculate number of shares (Position Size)
    quarterly_pf_stocks['shares'] = quarterly_pf_stocks['allocated_capital'] / quarterly_pf_stocks['entry_price']
    
    return quarterly_pf_stocks

# --------------------------------------------------------------------------------
# 2. DAILY EQUITY CURVE GENERATION (daily series of portfolio value)
# --------------------------------------------------------------------------------

def generate_quarter_equity_curve(
    trades: pd.DataFrame,
    price_data: pd.DataFrame,
    quarter: int,
    entry_price_window: int = DEFAULT_ENTRY_PRICE_WINDOW,
    risk_free_rate_annual: Optional[float] = None,
) -> pd.DataFrame:
    """
    Creates a daily series of portfolio value with explicit cash tracking.

    trades: [quarter, co_name, cat, stock_weight, exit_date, entry_price, exit_price, allocated_capital, shares]
    (already filtered for the target quarter)
    price_data: [date, co_name, open, high, low, close]
    quarter: integer like 202402
    entry_price_window: Number of trading days used for entry (must match the window used in trade simulation)
    risk_free_rate_annual: If set, idle cash earns this annual rate (compounded daily).
        When None, Cash_In_Hand is still tracked but does not appreciate.

    Returns a dataframe with index: dates in the quarter
        and columns Total_Portfolio_Value and Cash_In_Hand
    """
    # 1. Determine the Date Range of the quarter
    quarter_start_date, quarter_end_date = get_quarter_dates(quarter)

    # 2. Identify the entry phase trading days for this quarter
    all_dates_from_start = pd.DatetimeIndex(
        price_data.loc[price_data['date'] >= quarter_start_date, 'date'].unique()
    ).sort_values()
    if len(all_dates_from_start) >= entry_price_window:
        entry_phase_dates = all_dates_from_start[:entry_price_window]
    else:
        raise ValueError(f"Not enough trading days in quarter {quarter} to start the entry phase. Need {entry_price_window} days, got {len(all_dates_from_start)}.")

    # date_range extracts trading days from the price data itself
    date_range = all_dates_from_start[all_dates_from_start <= quarter_end_date]

    # 3. Prepare Price Data for Fast Lookup
    price_pivot = price_data.pivot(index='date', columns='co_name', values='close')
    # Filter only to our exact trading days (No reindex with 'B', no ffill)
    price_pivot = price_pivot.loc[date_range]

    # Initialise daily_values dataframe
    daily_values = pd.DataFrame(index=date_range)

    # Compute uninvested cash at the start of the quarter
    uninvested_cash = 0.0
    invalid_entry_mask = trades['entry_price'].isna()
    if invalid_entry_mask.any():
        invalid_stocks = trades.loc[invalid_entry_mask, 'co_name'].tolist()
        uninvested_cash = trades.loc[invalid_entry_mask, 'allocated_capital'].sum()
        warnings.warn(
            f"Entry price is NaN for {len(invalid_stocks)} stock(s): {invalid_stocks}. "
            f"Holding ₹{uninvested_cash/1_00_00_000:.2f} Cr as cash.",
            UserWarning
        )
        trades = trades[~invalid_entry_mask].copy()

    # Track cash inflows generated by exits
    cash_inflows = pd.Series(0.0, index=date_range)
    
    # Initialise running_cash to uninvested_cash
    running_cash = uninvested_cash

    # 4. Vectorized Equity Calculation
    stock_cols = []
    for _, row in trades.iterrows():
        co_name = row['co_name']
        shares = row['shares']
        entry_price = row['entry_price']
        exit_date = pd.Timestamp(row['exit_date'])

        # Initialize the column with scaled market prices
        if co_name in price_pivot.columns:
            stock_position_value = price_pivot[co_name] * shares
            if stock_position_value.isna().any():
                missing_dates = stock_position_value[stock_position_value.isna()].index.strftime('%Y-%m-%d').tolist()
                raise ValueError(f"Missing price data detected for {co_name} on the following dates: {missing_dates}. ")
        else:
            raise ValueError(f"Stock {co_name} not found in price data.")

        # Apply Entry Phase logic
        entry_mask = stock_position_value.index.isin(entry_phase_dates)
        stock_position_value.loc[entry_mask] = entry_price * shares

        # Apply Exit Phase logic (Zero out equity, move to cash)
        # NaT exit_date means position is still open — skip zeroing out.
        if pd.notna(exit_date):
            exit_mask = stock_position_value.index >= exit_date
            stock_position_value.loc[exit_mask] = 0.0

        # Update the dataframe
        daily_values[co_name] = stock_position_value
        stock_cols.append(co_name)

        # Record Cash Inflow (skip for open positions with NaT exit)
        if pd.notna(exit_date) and pd.notna(row['exit_price']):
            exit_proceeds = shares * row['exit_price']
            if exit_date < date_range[0]:
                raise ValueError(f"Exit date of stock {co_name} in quarter {quarter} has exit date {exit_date} before start date {date_range[0]}.")
            elif exit_date in cash_inflows.index:
                cash_inflows.loc[exit_date] += exit_proceeds
            else:
                raise ValueError(f"Exit date of stock {co_name} in quarter {quarter} has exit date {exit_date} out of regular date range.")

    # 5. Compute Cash_In_Hand through the quarter

    # Compute daily rate of appreciation
    r_daily = 0.0
    if risk_free_rate_annual is not None and risk_free_rate_annual > 0:
        r_daily = (1 + risk_free_rate_annual) ** (1 / TRADING_DAYS_PER_YEAR) - 1

    cash_series = np.empty(len(date_range))
    r_multiplier = 1 + r_daily if r_daily > 0 else 1.0

    for idx in range(len(date_range)):
        if idx > 0:
            running_cash *= r_multiplier  # first, appreciate the cash holding of the previous day
        running_cash += cash_inflows.iloc[idx]  # then, account for cash inflows
        cash_series[idx] = running_cash

    daily_values['Cash_In_Hand'] = cash_series

    # Total Value is the sum of all stock columns plus cash
    daily_values['Total_Portfolio_Value'] = daily_values[stock_cols].sum(axis=1) + cash_series

    return daily_values


def _generate_quarter_sequence(first_quarter: int, last_quarter: int) -> list[int]:
    """
    Generates a list of quarters between first_quarter and last_quarter (inclusive).
    Quarters are in format YYYYMM where MM is one of [02, 05, 08, 11].
    """
    quarter_months = [2, 5, 8, 11]
    
    first_quarter_year = int(str(first_quarter)[:4])
    first_quarter_month = int(str(first_quarter)[4:])
    
    quarters = []
    current_quarter_year = first_quarter_year
    current_quarter_month_idx = quarter_months.index(first_quarter_month)
    
    while True:
        current_quarter_month = quarter_months[current_quarter_month_idx]
        current_quarter = current_quarter_year * 100 + current_quarter_month
        
        if current_quarter > last_quarter:
            break
            
        quarters.append(current_quarter)
        
        # Move to next quarter
        current_quarter_month_idx += 1
        if current_quarter_month_idx >= len(quarter_months):
            current_quarter_month_idx = 0
            current_quarter_year += 1
    
    return quarters


def compute_portfolio_value_over_quarter(
    trades: pd.DataFrame,
    price_data: pd.DataFrame,
    target_quarter: int,
    initial_capital: float = INITIAL_CAPITAL,
    entry_price_window: int = DEFAULT_ENTRY_PRICE_WINDOW,
    risk_free_rate_annual: Optional[float] = None,
) -> Optional[pd.DataFrame]:
    '''
    trades: [quarter, co_name, cat, stock_weight, exit_date, entry_price, exit_price]
    price_data: [date, co_name, open, high, low, close]
    target_quarter: integer like 202402
    initial_capital: sum like 100 crs
    entry_price_window: Number of trading days used for entry (must match the window used in trade simulation)
    risk_free_rate_annual: If set, idle cash earns this annual rate.

    Returns a dataframe with index: dates in the quarter
        and columns Total_Portfolio_Value and Cash_In_Hand
    '''
    quarter_df = trades[trades['quarter'] == target_quarter].copy()
    if quarter_df.empty:
        raise ValueError(f"No data found for quarter {target_quarter}")

    quarter_df_sized = calculate_position_sizes(quarter_df, initial_capital)

    equity_curve = generate_quarter_equity_curve(
        quarter_df_sized, price_data, target_quarter, entry_price_window,
        risk_free_rate_annual=risk_free_rate_annual,
    )

    return equity_curve


def compute_portfolio_value_over_quarters(
    trades: pd.DataFrame,
    price_data: pd.DataFrame,
    first_quarter: int,
    last_quarter: int,
    initial_capital: float = INITIAL_CAPITAL,
    entry_price_window: int = DEFAULT_ENTRY_PRICE_WINDOW,
    risk_free_rate_annual: Optional[float] = None,
) -> Optional[pd.DataFrame]:
    '''
    Computes portfolio value across multiple quarters at daily frequency.
    The ending value of each quarter becomes the starting capital for the next quarter.

    trades: [quarter, co_name, cat, stock_weight, exit_date, entry_price, exit_price]
    price_data: [date, co_name, open, high, low, close]
    first_quarter: integer like 202402 (start quarter, inclusive)
    last_quarter: integer like 202411 (end quarter, inclusive)
    initial_capital: sum like 100 crs
    entry_price_window: Number of trading days used for entry (must match the window used in trade simulation)
    risk_free_rate_annual: If set, idle cash earns this annual rate.

    Returns a dataframe with index: dates across all quarters
        and columns Total_Portfolio_Value and Cash_In_Hand
    '''
    quarters = _generate_quarter_sequence(first_quarter, last_quarter)
    
    if not quarters:
        raise ValueError("No valid quarters in the specified range.")
    
    all_equity_curves = []
    current_capital = initial_capital
    
    for quarter in quarters:
        equity_curve = compute_portfolio_value_over_quarter(
            trades, price_data, quarter, current_capital, entry_price_window,
            risk_free_rate_annual=risk_free_rate_annual,
        )
        
        if equity_curve is None or equity_curve.empty:
            raise ValueError(f"equity curve is empty for {quarter}.")
        
        equity_curve = equity_curve[['Total_Portfolio_Value', 'Cash_In_Hand']].copy()
        equity_curve['quarter'] = quarter
        all_equity_curves.append(equity_curve)
        
        current_capital = equity_curve['Total_Portfolio_Value'].iloc[-1]
    
    if not all_equity_curves:
        raise ValueError("No equity curves generated for any quarter.")
    
    combined_equity_curve = pd.concat(all_equity_curves)
    
    duplicated_dates = combined_equity_curve.index[combined_equity_curve.index.duplicated(keep=False)]
    if len(duplicated_dates) > 0:
        raise ValueError(f"Found overlapping dates between quarters.")
    
    combined_equity_curve = combined_equity_curve.sort_index()
    
    return combined_equity_curve


def compute_portfolio_vs_index(trades: pd.DataFrame, price_data: pd.DataFrame, index_price_data: pd.DataFrame, first_quarter: int, last_quarter: int, initial_capital: float = INITIAL_CAPITAL, daily_pf_values: Optional[pd.DataFrame] = None) -> Optional[pd.DataFrame]:
    '''
    Computes portfolio performance vs benchmark index across multiple quarters.

    trades: [quarter, co_name, cat, stock_weight, exit_date, entry_price, exit_price]
    price_data: [date, co_name, open, high, low, close]
    index_price_data: [date, value] - benchmark index values
    first_quarter: integer like 202402 (start quarter, inclusive)
    last_quarter: integer like 202411 (end quarter, inclusive)
    initial_capital: sum like 100 crs
    daily_pf_values: Pre-computed equity curve (optional). If provided, skips recomputation
                     to ensure consistency with backtest_core output.

    Returns a dataframe with columns:
        - date: the date
        - pf_value: portfolio value on that date
        - pf_return: portfolio return vs initial capital (%)
        - index_fund_value: value if initial capital was invested in index
        - index_return: index fund return vs initial capital (%)
        - alpha: pf_return - index_return (%)
    '''
    # Get portfolio equity curve (reuse if provided, otherwise compute)
    if daily_pf_values is None:
        daily_pf_values = compute_portfolio_value_over_quarters(
            trades, price_data, first_quarter, last_quarter, initial_capital
        )
    
    if daily_pf_values is None or daily_pf_values.empty:
        logger.warning("No portfolio data found.")
        return None
    
    # Prepare index data
    index_data = index_price_data.copy()
    index_data['date'] = pd.to_datetime(index_data['date'])
    index_data = index_data.set_index('date').sort_index()
    
    # Get the date range from portfolio equity curve
    pf_dates = daily_pf_values.index
    start_date = pf_dates[0]
    end_date = pf_dates[-1]
    
    # Filter index data to match portfolio date range
    index_data = index_data[(index_data.index >= start_date) & (index_data.index <= end_date)]
    
    # Reindex index data to match portfolio dates (forward fill for missing dates)
    index_data = index_data.reindex(pf_dates).ffill()
    
    # Get initial index value (first date's value)
    initial_index_value = index_data['value'].iloc[0]
    
    if pd.isna(initial_index_value):
        warnings.warn(
            f"No index data found for start date {start_date.date()}. "
            f"Using first available index value.",
            UserWarning
        )
        initial_index_value = index_data['value'].dropna().iloc[0]
    
    # Compute index fund value: initial_capital * (current_index / initial_index)
    index_fund_value = initial_capital * (index_data['value'] / initial_index_value)
    
    # Build result dataframe
    result = pd.DataFrame({
        'date': pf_dates,
        'pf_value': daily_pf_values['Total_Portfolio_Value'].values,
        'index_fund_value': index_fund_value.values
    })
    
    # Compute returns (as percentage)
    result['pf_return'] = ((result['pf_value'] - initial_capital) / initial_capital) * 100
    result['index_return'] = ((result['index_fund_value'] - initial_capital) / initial_capital) * 100
    
    # Compute alpha (outperformance)
    result['alpha'] = result['pf_return'] - result['index_return']
    
    # Reorder columns
    result = result[['date', 'pf_value', 'pf_return', 'index_fund_value', 'index_return', 'alpha']]
    
    return result